import { A as e, D as t, a as r, b as E, c as _, d as S, e as T, R as A, f as R, g as i, h as o, i as g, j as n, k as D, l as F, m as L, n as M, o as l, r as U, p as c, s as f, q as I, v as Y } from "./c2pa-CL7pqSPf.js";
export {
  e as AssetTooLargeError,
  t as DEFAULT_INITIAL_RETRY_DELAY_MS,
  r as DEFAULT_MAX_RESPONSE_BYTES,
  E as DEFAULT_MAX_RETRIES,
  _ as DEFAULT_MAX_RETRY_AFTER_MS,
  S as DEFAULT_MAX_RETRY_DELAY_MS,
  T as DEFAULT_MAX_SIZE_IN_BYTES,
  A as READER_SUPPORTED_FORMATS,
  R as createC2pa,
  i as createCawgTrustSettings,
  o as createTrustSettings,
  g as createVerifySettings,
  n as defaultIsRetryableStatus,
  D as fetchWithRetry,
  F as fetchWithRetryRaw,
  L as isSupportedReaderFormat,
  M as loadSettingsFromUrl,
  l as mergeSettings,
  U as resolveSettings,
  c as resolveTrustSettings,
  f as settingsToJson,
  I as snakeCaseify,
  Y as validateAssetSize
};
